name: Build and Test

on:
    push:
    pull_request:
        types:
            - opened
            - reopened
            - ready_for_review

env:
    CARGO_TERM_COLOR: always
    SCCACHE_GHA_ENABLED: "false"
    RUSTC_WRAPPER: "sccache"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check rust toolchain version
              run: |
                cargo version
                rustc --version
                rustup toolchain list
            - name: Build rust
              run: cargo build
            - name: Generate witness
              run: cargo test
